package com.zhenghuanrong.pojo;

public class course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cno
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cname
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.semester
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    private Integer semester;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cno
     *
     * @return the value of course.cno
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cno
     *
     * @param cno the value for course.cno
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cname
     *
     * @return the value of course.cname
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cname
     *
     * @param cname the value for course.cname
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.semester
     *
     * @return the value of course.semester
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public Integer getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.semester
     *
     * @param semester the value for course.semester
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    public void setSemester(Integer semester) {
        this.semester = semester;
    }
}