package com.zhenghuanrong.pojo;

import java.util.Date;

public class emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Workshop
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    private String workshop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.time
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salary
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    private Integer salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Workshop
     *
     * @return the value of employee.Workshop
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public String getWorkshop() {
        return workshop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Workshop
     *
     * @param workshop the value for employee.Workshop
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public void setWorkshop(String workshop) {
        this.workshop = workshop == null ? null : workshop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.time
     *
     * @return the value of employee.time
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.time
     *
     * @param time the value for employee.time
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salary
     *
     * @return the value of employee.salary
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.salary
     *
     * @param salary the value for employee.salary
     *
     * @mbggenerated Thu Mar 02 17:04:46 CST 2023
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        return "emp{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", workshop='" + workshop + '\'' +
                ", time=" + time +
                ", salary=" + salary +
                '}';
    }
}