package com.zhenghuanrong.mapper;

import com.zhenghuanrong.pojo.course;
import com.zhenghuanrong.pojo.courseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int countByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int deleteByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int deleteByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int insert(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int insertSelective(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    List<course> selectByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    course selectByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int updateByExampleSelective(@Param("record") course record, @Param("example") courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int updateByExample(@Param("record") course record, @Param("example") courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int updateByPrimaryKeySelective(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Mar 02 17:35:55 CST 2023
     */
    int updateByPrimaryKey(course record);
}